name: pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  uv:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v10

      - name: Install the Project
        run: uv sync --locked

      - name: Run Tests
        run: uv run pytest